---
- name: Install epel-release
  yum:
    name: epel-release
    state: present
    update_cache: yes
- name: Install nginx web server
  yum:
    name: nginx
    state: present 
  notify:
  - Start nginx

